### ISSUE TITLE
L2A_Process not found

### ISSUE THREAD

**Issue by sholtkamp** [sholtkamp/pre_processing#1]
Running the batchfile apply_sen2cor.bat doesn't work properly.

The image is built correctly. Running a container from the image causes following error:

`C:\Users\---\Documents\GitHub\pre_processing\pre_processing>docker run --rm --name=apply_container --mount type=bind,source=C:\Users\---\Documents \GitHub\pre_processing\pre_processing\..\data, target=/workspace/data -e imgfolder=/workspace/data apply`
`sh: 1: L2A_Process: not found`
`1 level 1C file(s) found. Performing atmospheric correction.` 
`Done.`

No products are generated even though calculation is "done".

**Comment by nuest** [comment]
When building the container, I get a lot of "No such file or directory" log messages. Are those normal?

```
[...]
018-11-21 12:51:32 (19.7 MB/s) - 'Sen2Cor-02.05.05-Linux64.run' saved [238206424/238206424]
Creating directory Sen2Cor-02.05.05-Linux64
  54% Verifying archive integrity... All good.
Uncompressing SEN2COR 0 100%
Configuring...
find: 'file': No such file or directory
find: 'file': No such file or directory
find: 'file': No such file or directory
find: 'file': No such file or directory
find: 'file': No such file or directory
find: 'file': No such file or directory
[...]
find: 'file': No such file or directory
find: 'file': No such file or directory
copying /Sen2Cor-02.05.05-Linux64/lib/python2.7/site-packages/sen2cor/cfg/L2A_GIPP.xml to /root/sen2cor/2.5/cfg/L2A_GIPP.xml!
Congratulations, Installation successful...
You can call L2A processor with '/Sen2Cor-02.05.05-Linux64/bin/L2A_Process'
Default configuration file is '/root/sen2cor/2.5/cfg/L2A_GIPP.xml'
Removing intermediate container a08f793999c3
[..]
```

I actually have problems running `L2A_Process` in the container, so I am surprised the Python script works... do you get the help output with the following command?

```bash
docker run --rm -it -v ${PWD}/data:/workspace/data -e imgfolder=/workspace/data --entrypoint=/bin/bash monconfsat_pre L2A_Process --help
```

Other than that, maybe setting the `Log_Level` to `DEBUG` in `/root/sen2cor/2.5/cfg/L2A_GIPP.xml` within the container might help finding issues.
